export const POSTS = [
	{
		_id: "1",
		text: "Im in love with Frank G. Cagadas Yall",
		img: "/posts/post1.png",
		user: {
			username: "kurtieboi",
			profileImg: "/avatars/boy1.png",
			fullName: "Kurt Frances",
		},
		comments: [
			{
				_id: "1",
				text: "Me too",
				user: {
					username: "normie",
					profileImg: "/avatars/girl1.png",
					fullName: "Norman Asakil",
				},
			},
		],
		likes: ["6658s891", "6658s892", "6658s893", "6658s894"],
	},
	{
		_id: "2",
		text: "Samal na ta",
		user: {
			username: "joblessreincarnation",
			profileImg: "/avatars/boy2.png",
			fullName: "John Robles",
		},
		comments: [
			{
				_id: "1",
				text: "Nov 20 pa oy",
				user: {
					username: "kurtieboi",
					profileImg: "/avatars/girl2.png",
					fullName: "Kurt Frances",
				},
			},
		],
		likes: ["6658s891", "6658s892", "6658s893", "6658s894"],
	},
	{
		_id: "3",
		text: "Astronaut in a room of drawers, generated by Midjourney. 🚀",
		img: "/posts/post2.png",
		user: {
			username: "johndoe",
			profileImg: "/avatars/boy3.png",
			fullName: "John Doe",
		},
		comments: [],
		likes: ["6658s891", "6658s892", "6658s893", "6658s894", "6658s895", "6658s896"],
	},
	{
		_id: "4",
		text: "I'm learning GO this week. Any tips? 🤔",
		img: "/posts/post3.png",
		user: {
			username: "johndoe",
			profileImg: "/avatars/boy3.png",
			fullName: "John Doe",
		},
		comments: [
			{
				_id: "1",
				text: "Nice Tutorial",
				user: {
					username: "janedoe",
					profileImg: "/avatars/girl3.png",
					fullName: "Jane Doe",
				},
			},
		],
		likes: [
			"6658s891",
			"6658s892",
			"6658s893",
			"6658s894",
			"6658s895",
			"6658s896",
			"6658s897",
			"6658s898",
			"6658s899",
		],
	},
];
